/**
 * by CntChen 2016.02.26
 */

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const SET_LOGIN_STATE_TO_HAS_LOGIN = 'SET_LOGIN_STATE_TO_HAS_LOGIN';
export const SET_LOGIN_STATE_TO_HAS_LOGOUT = 'SET_LOGIN_STATE_TO_HAS_LOGOUT';
export const SET_LOGIN_STATE_TO_REGISTER = 'SET_LOGIN_STATE_TO_REGISTER';